# Generated by Django 4.2.4 on 2024-03-08 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_alter_collectible_product_alter_collectible_series'),
        ('trades', '0002_rename_image_trade_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='images',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='requesting1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting1', to='collectibles.collectible'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='requesting2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting2', to='collectibles.collectible'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='requesting3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting3', to='collectibles.collectible'),
        ),
    ]
