# Generated by Django 4.2.4 on 2024-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_trade_description_alter_trade_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('verified', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
