# Generated by Django 4.2.4 on 2024-03-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_img'),
        ('collectibles', '0003_alter_collectible_product_alter_collectible_series'),
        ('trades', '0004_image_trade_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='images',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='requesting1',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='requesting2',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='requesting3',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trading',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='verified',
        ),
        migrations.AddField(
            model_name='trade',
            name='profileOne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOne', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='trade',
            name='profileOneAccepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='profileTwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileTwo', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='trade',
            name='profileTwoAccepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(blank=True, default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('images', models.TextField(blank=True, default='', null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('trading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading', to='collectibles.collectible')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='givingOne',
            field=models.ManyToManyField(blank=True, related_name='givingOne', to='trades.listing'),
        ),
        migrations.AddField(
            model_name='trade',
            name='givingTwo',
            field=models.ManyToManyField(blank=True, related_name='givingTwo', to='trades.listing'),
        ),
    ]
