# Generated by Django 4.2.4 on 2024-03-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_remove_trade_description_remove_trade_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='trading',
            new_name='collectible',
        ),
    ]
