# Generated by Django 4.2.4 on 2024-02-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectibles', '0003_alter_collectible_product_alter_collectible_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='')),
                ('collection', models.ManyToManyField(blank=True, related_name='collection', to='collectibles.collectible')),
            ],
        ),
    ]
