# Generated by Django 4.2.4 on 2024-02-21 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectibles', '0003_alter_collectible_product_alter_collectible_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trades',
            field=models.ManyToManyField(blank=True, related_name='trades', to='trades.trade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='collectibles.collectible'),
        ),
    ]
