# Generated by Django 4.2.4 on 2024-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_alter_collectible_product_alter_collectible_series'),
        ('trades', '0001_initial'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collection',
            field=models.ManyToManyField(blank=True, default=None, related_name='collection', to='collectibles.collectible'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trades',
            field=models.ManyToManyField(blank=True, default=None, related_name='trades', to='trades.trade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='wishlist', to='collectibles.collectible'),
        ),
    ]
