# Generated by Django 4.2.4 on 2024-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_profile_img_profile_raters_profile_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
