# Generated by Django 4.2.4 on 2024-04-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_alter_collectible_product_alter_collectible_series'),
        ('profiles', '0006_alter_profile_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorites', to='collectibles.collectible'),
        ),
    ]
