# Generated by Django 4.2.4 on 2024-04-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_listing_user'),
        ('profiles', '0007_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorites', to='trades.listing'),
        ),
    ]
