# Generated by Django 4.2.4 on 2024-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_listing_user'),
        ('profiles', '0008_alter_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, default=None, related_name='saved', to='trades.listing'),
        ),
    ]
