# Generated by Django 4.2.4 on 2024-04-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_alter_collectible_product_alter_collectible_series'),
        ('profiles', '0009_profile_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_collection',
            field=models.ManyToManyField(blank=True, default=None, related_name='in_collection', to='collectibles.collectible'),
        ),
    ]
